apiVersion: v1
kind: Service
metadata:
  name: cv-fit-score
  namespace: default
spec:
  selector:
    app: cv-fit-score
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
